name: "transformer"
version: "1.0.0"

profile: "transformer"

model-paths: ["transformer/models"]
analysis-paths: ["transformer/analyses"]
test-paths: ["transformer/tests"]
seed-paths: ["transformer/seeds"]
macro-paths: ["transformer/macros"]
snapshot-paths: ["transformer/snapshots"]

clean-targets: # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"
